/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ResourceCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "resourceCategory";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  shortDescription?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  externalUrl: string;
  category: ResourceCategoryReference;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ResourceCategory = {
  _id: string;
  _type: "resourceCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  author?: string;
  publishedAt: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type DailySummary = {
  _id: string;
  _type: "dailySummary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  careRecipientName: string;
  relationship?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  moodStatus?: "calm" | "restless" | "engaged" | "sleeping";
  shortSummary?: string;
  notesOrFlags?: Array<string>;
  activities?: Array<{
    title: string;
    time?: string;
    note?: string;
    _type: "activity";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ResourceCategoryReference
  | Resource
  | SanityImageCrop
  | SanityImageHotspot
  | ResourceCategory
  | Slug
  | BlogPost
  | DailySummary
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: dailySummaryQuery
// Query: *[_type == "dailySummary" && _id == "dailySummary"][0]{    careRecipientName,    relationship,    photo,    moodStatus,    shortSummary,    notesOrFlags,    activities[]{ title, time, note }  }
export type DailySummaryQueryResult = {
  careRecipientName: string;
  relationship: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  moodStatus: "calm" | "engaged" | "restless" | "sleeping" | null;
  shortSummary: string | null;
  notesOrFlags: Array<string> | null;
  activities: Array<{
    title: string;
    time: string | null;
    note: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    author,    publishedAt,    featuredImage,    excerpt  }
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  author: string | null;
  publishedAt: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  excerpt: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    author,    publishedAt,    featuredImage,    excerpt,    body  }
export type PostBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  author: string | null;
  publishedAt: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: postSlugsQuery
// Query: *[_type == "blogPost" && defined(slug.current)][].slug.current
export type PostSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: resourcesByCategoryQuery
// Query: *[_type == "resourceCategory"] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "resources": *[_type == "resource" && references(^._id)] | order(title asc){      _id,      title,      shortDescription,      thumbnail,      externalUrl    }  }
export type ResourcesByCategoryQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  resources: Array<{
    _id: string;
    title: string;
    shortDescription: string | null;
    thumbnail: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    externalUrl: string;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "dailySummary" && _id == "dailySummary"][0]{\n    careRecipientName,\n    relationship,\n    photo,\n    moodStatus,\n    shortSummary,\n    notesOrFlags,\n    activities[]{ title, time, note }\n  }\n': DailySummaryQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    author,\n    publishedAt,\n    featuredImage,\n    excerpt\n  }\n': AllPostsQueryResult;
    '\n  *[_type == "blogPost" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    author,\n    publishedAt,\n    featuredImage,\n    excerpt,\n    body\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current)][].slug.current\n': PostSlugsQueryResult;
    '\n  *[_type == "resourceCategory"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "resources": *[_type == "resource" && references(^._id)] | order(title asc){\n      _id,\n      title,\n      shortDescription,\n      thumbnail,\n      externalUrl\n    }\n  }\n': ResourcesByCategoryQueryResult;
  }
}
